name: Convert a README.md file to a Word document
on:
  push:
    branches:
      - main

jobs:
  convert-readme-md-to-docx:
    name: Convert README.md to README.docx
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install pandoc
        run: |
          # Pandoc features can break, so freeze the version by not using the repo version
          wget -O /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb \
            && sudo dpkg -i /tmp/pandoc.deb
          pandoc --version 

      - name: Convert README.md to README.docx
        run: |
          pandoc -f gfm -t docx -o README.docx ./README.md
          ls -l README.docx 

      - name: Create release of README.docx
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: README.docx v${{ github.run_number }}
          draft: false
          prerelease: false 

      - name: Upload README.docx
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./README.docx
          asset_name: README.docx
          asset_content_type: application/octet-stream

      #- name: Create Issue for a failed deployment
      #  if: ${{ failure() }}
      #  uses: dacbd/create-issue-action@main
      #  with:
      #    token: ${{ github.token }}
      #    title: Action workflow failed.
      #    body: |
      #      ### Context
      #      [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
      #      [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
      #      Workflow name - `${{ github.workflow }}`
      #      Job -           `${{ github.job }}`
      #      status -        `${{ job.status }}`
        
